apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  namespace: demo
spec:
  selector:
    app: welcome-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
