apiVersion: v1
kind: Service
metadata:
  name: welcome-app-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: welcome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
